//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicCRUDApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string Emp_ID { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string Phone_No { get; set; }
        public string Address { get; set; }
    }
}
